name: Build for all platforms
on:
  push:
    branches: [master]
 
jobs:
  Android_build:
    runs-on: ubuntu-18.04
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2
    - name: DEV SETP UP
      run: npm run dev-setup
     
    - name: Trigger Android Linux build
      run: cd template && cd android && ./gradlew assembleRelease --stacktrace
 
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: app-release.apk
        path: template/android/app/build/outputs/apk/release
